name: AI PR Reviewer

on:
  pull_request:
    types: [opened, synchronize]

permissions: #권한설정
  contents: read
  pull-requests: write

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: AI Code Review
        uses: tmknom/openai-code-reviewer-action@v0
        with:
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # 한국어 리뷰
          LANGUAGE: Korean
          MODEL: gpt-4o # 또는 gpt-3.5-turbo